# Is the same command twice in a row the same file, every time?
#
# This exists because of a bug that bit-exactness testing structurally CANNOT
# find.  The unfilled-channel fault in ImStore (see ZeroQueuedRow in src/rd_im.cpp)
# made the PNG coder choose a different encoding -- TrueColorAlpha, PaletteAlpha,
# Gray, Bilevel -- from whatever stale heap memory happened to be in the fifth
# channel.  Both engines went through the same writer, so comparing OpenCL against
# CUDA found nothing: they were wrong in the same way at the same time, roughly a
# third of runs' worth of agreement.  The probe-opencl-exact.ps1 sweep only caught
# it because it happened to run enough cells for the coin flips to disagree.
#
# A test that compares two implementations cannot see a fault they share.  This
# one compares an implementation against ITSELF across time, which is the only
# thing that sees it.  Two rules follow, and both are load-bearing:
#
#   * Repeat a case enough times to see an intermittent fault.  Once is not a
#     test of determinism; it is a test of luck.  The default here is 12, and the
#     fault showed up in 3 runs of 16 -- so 12 is comfortably past the point where
#     a regression cannot hide.
#
#   * Hash the DECODED PIXELS, and hash the file WITH METADATA STRIPPED.  Not the
#     raw file.  ImageMagick writes a `png:tIME` chunk recording when the file was
#     written, so two runs a second apart produce different bytes from identical
#     pixels -- measured here at 5 distinct files over 6 runs, with 1 distinct
#     pixel set and 1 distinct stripped file.  That is PNG doing its job, not a
#     fault, and no image tool promises byte-identical files across time.  (If
#     byte-reproducible output is wanted, `png:exclude-chunk=date,time` on the
#     write does it; it is not the default here because this project's stated bar
#     is matching ImageMagick's *pixels*, per DESIGN.md section 8 item 5.)
#
#     Comparing stripped bytes rather than giving up on the file is what makes the
#     second half of this test worth running: "the encoder picked a different type
#     again" is a real bug and shows up as differing stripped files, while a
#     timestamp shows up as differing raw files with identical stripped ones.
#
# Every engine is swept, not just the GPU ones.  The fault was worse on OpenCL only
# because its extra host allocations rearranged the heap; it was present on all of
# them, and a test that only watches the fast path will call the bug flaky.

param(
  [string]$Dir = "$env:TEMP\rdocl",
  [int]$Runs = 12
)

# NOT 'Stop'.  rdither writes diagnostics to stderr, and a native command's stderr
# surfaces as a non-terminating error record; under 'Stop' the first "[blocks]"
# notice aborts the sweep before it starts.  Failure is detected from exit codes
# and from the decoded hash count, which are the things that actually mean failure.
$ErrorActionPreference = 'Continue'
$rd = Join-Path (Split-Path $PSScriptRoot -Parent) 'build\Release\rdither.exe'
if (-not (Test-Path $rd)) { "missing $rd -- build first"; exit 1 }
if (-not (Test-Path $Dir)) { New-Item -ItemType Directory -Force -Path $Dir | Out-Null }

# Same images the OpenCL sweep uses, so a regression in either is the same
# regression.  c_ashape and c_alpha50 carry alpha; c_plasma and c_noise do not.
$imgs = @('c_plasma', 'c_ashape')
$engines = @('cpu', 'blocks', 'opencl')

# Missing fixtures are "cannot test", which is not the same as "failed", and
# reporting one as the other is how a broken test gets trusted.  Exit 2 says so.
$missing = @($imgs | Where-Object { -not (Test-Path "$Dir\$_.png") })
if ($missing.Count -gt 0) {
  ''
  "cannot run: no fixture for $($missing -join ', ') in $Dir"
  'these are generated by tools\probe-opencl-exact.ps1 -- run that once first'
  exit 2
}

# Decode to raw RGBA through cmd /c rather than the PowerShell pipeline.  A native
# command's stdout piped through PowerShell is re-encoded, which turns the binary
# into text and destroys the very thing being hashed.
function Get-PixelHash([string]$png) {
  $raw = [IO.Path]::ChangeExtension($png, '.raw')
  Remove-Item -EA SilentlyContinue $raw
  cmd /c "magick ""$png"" -depth 8 ""rgba:$raw""" 2>$null | Out-Null
  if (-not (Test-Path $raw)) { return $null }
  $h = (Get-FileHash $raw -Algorithm SHA256).Hash
  Remove-Item -EA SilentlyContinue $raw
  return $h
}

# The same file with metadata removed, so a tIME difference does not register as an
# encoder difference.  -strip rewrites through IM rather than editing bytes, so it
# also re-runs the encoder -- which means this hash is only meaningful because the
# pixels have already been checked: if the pixels are stable and this varies, the
# encoder really is choosing differently.
function Get-StrippedHash([string]$png) {
  $tmp = [IO.Path]::ChangeExtension($png, '.strip.png')
  Remove-Item -EA SilentlyContinue $tmp
  cmd /c "magick ""$png"" -strip ""$tmp""" 2>$null | Out-Null
  if (-not (Test-Path $tmp)) { return $null }
  $h = (Get-FileHash $tmp -Algorithm SHA256).Hash
  Remove-Item -EA SilentlyContinue $tmp
  return $h
}

$fail = 0
$total = 0
''
"Determinism: $Runs runs per case, decoded pixels"
''

foreach ($img in $imgs) {
  $src = "$Dir\$img.png"
  foreach ($eng in $engines) {
    $total++
    $pixelHashes = @{}
    $strippedHashes = @{}
    $rawHashes = @{}
    $bad = 0
    for ($i = 1; $i -le $Runs; $i++) {
      $out = "$Dir\det_${img}_${eng}_$i.png"
      # Delete first.  A run that fails leaves a stale file, and a stale file
      # hashes fine -- so a crashed engine would report as a stable engine, which
      # is the precise opposite of the truth.
      Remove-Item -EA SilentlyContinue $out
      & $rd --engine $eng --blocks 16 --colors 2 $src $out 2>$null | Out-Null
      if ($LASTEXITCODE -ne 0 -or -not (Test-Path $out)) { $bad++; continue }
      $ph = Get-PixelHash $out
      $sh = Get-StrippedHash $out
      if ($null -eq $ph -or $null -eq $sh) { $bad++; continue }
      $pixelHashes[$ph] = 1
      $strippedHashes[$sh] = 1
      $rawHashes[(Get-FileHash $out -Algorithm SHA256).Hash] = 1
      Remove-Item -EA SilentlyContinue $out
    }
    $np = $pixelHashes.Count
    $ns = $strippedHashes.Count
    $nr = $rawHashes.Count
    $tag = "{0,-8} {1,-7}" -f $img, $eng
    if ($bad -gt 0) {
      $fail++
      "  $tag  FAIL  $bad of $Runs runs produced no output"
    } elseif ($np -ne 1) {
      $fail++
      "  $tag  FAIL  $np distinct pixel sets over $Runs runs -- NOT DETERMINISTIC"
    } elseif ($ns -ne 1) {
      $fail++
      "  $tag  FAIL  pixels stable but $ns distinct files after -strip -- the encoder is the variable"
    } else {
      # Raw files differing while stripped files match is the tIME chunk, which is
      # PNG working as intended.  Worth surfacing, never worth failing on.
      $note = if ($nr -eq 1) { '' } else { "   ($nr raw files differ: png:tIME only)" }
      "  $tag  ok    1 pixel set, 1 stripped file, $Runs runs$note"
    }
  }
}

''
if ($fail -eq 0) {
  "{0} of {1} cases deterministic." -f ($total - $fail), $total
  exit 0
}
"{0} of {1} cases FAILED." -f ($total - $fail), $total
exit 1
